// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWB8_w_N6vvNlJEBWixuMl2fuWaqoJbRM',
    appId: '1:965306343868:web:c55cb9efa5aa772afbcbb9',
    messagingSenderId: '965306343868',
    projectId: 'flutter-fundoo-app',
    authDomain: 'flutter-fundoo-app.firebaseapp.com',
    storageBucket: 'flutter-fundoo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHGqPwcYU42sO3h6ozOR75cJno4pGXwk',
    appId: '1:965306343868:android:cc1d5e29afc6209efbcbb9',
    messagingSenderId: '965306343868',
    projectId: 'flutter-fundoo-app',
    storageBucket: 'flutter-fundoo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73xbnZgsLs5VKA59ym1ghNZJ3SnDSMLg',
    appId: '1:965306343868:ios:dbfca9be78379fa8fbcbb9',
    messagingSenderId: '965306343868',
    projectId: 'flutter-fundoo-app',
    storageBucket: 'flutter-fundoo-app.appspot.com',
    iosClientId: '965306343868-81eoj3r19htsgrjl0q12fvd9i3a2f0jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundooApp',
  );
}
